### ISSUE TITLE
Lacks appeal and personality.

### ISSUE THREAD

**Issue by bearcott** [ffejhog/ffejhog.github.io#2]
I checked the source and both "hello" and "world" are written in `Times New Roman`. I see no personality in this site. Additionally, neither "hello" nor "world" tell me about you as a person. 

At least you got the Hello part right. I suggest u change:

hello ~~world~~

to:

hello my name is Jeff

But even with that, I doubt you will be attracting any clients anytime soon.

**Comment by ffejhog** [comment]
Issue closed as I have no personality.
